cowegis_contao_backend_api_docs:
    path: /contao/cowegis/docs
    controller: Cowegis\Bundle\Contao\Action\Backend\DocsAction
    methods: [GET]
    defaults:
        _scope: backend
        _backend_module: cowegis-api-docs

cowegis_contao_backend_map_layer_actions:
    path: /contao/cowegis/map/{mapId}/layer/{layerId}
    controller: Cowegis\Bundle\Contao\Action\Backend\MapLayerAction
    methods: [POST]
    defaults:
        _scope: backend
