<?php

declare(strict_types=1);

use Contao\DC_Table;

$GLOBALS['TL_DCA']['tl_cowegis_layer'] = [
    'config' => [
        'dataContainer'    => DC_Table::class,
        'enableVersioning' => true,
        'ctable'           => ['tl_cowegis_marker'],
        'sql'              => [
            'keys' => [
                'id'  => 'primary',
                'pid' => 'index',
            ],
        ],
    ],
    'list'   => [
        'sorting'           => [
            'mode'        => 5,
            'fields'      => ['title'],
            'flag'        => 1,
            'rootPaste'   => true,
            'icon'        => 'bundles/cowegiscontao/img/layers.png',
            'panelLayout' => 'filter;search,limit',
        ],
        'label'             => [
            'fields' => ['title'],
            'format' => '%s',
        ],
        'global_operations' => [
            'toggleNodes' => [
                'href'         => 'ptg=all',
                'class'        => 'header_toggle',
                'showOnSelect' => true,
            ],
            'all'         => [
                'href'       => 'act=select',
                'class'      => 'header_edit_all',
                'attributes' => 'onclick="Backend.getScrollOffset();"',
            ],
        ],
        'operations'        => [
            'data'   => [
                'href' => '',
                'icon' => 'edit.svg',
            ],
            'edit'   => [
                'label' => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['edit'],
                'href'  => 'act=edit',
                'icon'  => 'header.gif',
            ],
            'copy'   => [
                'label' => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['copy'],
                'href'  => 'act=copy',
                'icon'  => 'copy.gif',
            ],
            'cut'    => [
                'label'      => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['cut'],
                'href'       => 'act=paste&amp;mode=cut',
                'icon'       => 'cut.gif',
                'attributes' => 'onclick="Backend.getScrollOffset()"',
            ],
            'delete' => [
                'label'      => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['delete'],
                'href'       => 'act=delete',
                'icon'       => 'delete.gif',
                'attributes' => 'onclick="if(!confirm(\'' . ($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? '')
                    . '\'))return false;Backend.getScrollOffset()"',
            ],
            'show'   => [
                'label' => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['show'],
                'href'  => 'act=show',
                'icon'  => 'show.gif',
            ],
        ],
    ],

    'palettes' => [
        '__selector__' => ['type'],
    ],

    'metapalettes' => [
        'default'                       => [
            'title'  => ['title', 'alias', 'type'],
            'config' => [],
            'style'  => [],
            'expert' => [':hide'],
        ],
        'markers extends default'       => [
            '+config'              => [
                'attribution',
                'draggable',
                'interactive',
                'keyboard',
                'opacity',
                'zIndexOffset',
                'riseOnHover',
            ],
            'marker before config' => [
                'icon',
                'popup',
                'tooltip',
            ],
            '+style'               => [],
            '+expert'              => ['pointToLayer', 'deferred'],
        ],
        'group extends default'         => [
            '+title'  => ['groupType'],
            '+active' => [],
        ],
        'vectors extends default'       => [
            '+expert' => ['onEachFeature', 'pointToLayer'],
            '+config' => ['vectors', 'deferred'],
        ],
        'reference extends default'     => [
            '+title' => ['reference', 'standalone'],
        ],
        'markerCluster extends default' => [
            'config'  => [
                'showCoverageOnHover',
                'zoomToBoundsOnClick',
                'removeOutsideVisibleBounds',
                'animateAddingMarkers',
                'spiderfyOnMaxZoom',
                'disableClusteringAtZoom',
                'maxClusterRadius',
                'singleMarkerMode',
            ],
            '+expert' => [
                'polygonOptions',
                'iconCreateFunction',
            ],
        ],
        'tileLayer extends default'     => [
            'config'  => [
                'tileUrl',
                'subdomains',
                'attribution',
                'minZoom',
                'maxZoom',
            ],
            '+expert' => [
                'errorTileUrl',
                'tileSize',
                'tms',
                'noWrap',
                'zoomReverse',
                'zoomOffset',
                'maxNativeZoom',
                'opacity',
                'zIndex',
                'unloadvisibleTiles',
                'updateWhenIdle',
                'detectRetina',
                'bounds',
            ],
        ],
        'overpass extends default'      => [
            'config'  => [
                'overpassQuery',
                'minZoom',
                'overpassEndpoint',
                'overpassPopup',
            ],
            'style'   => ['amenityIcons'],
            '+expert' => [
                'onEachFeature',
                'pointToLayer',
            ],
        ],

        'file extends default' => [
            '+config' => ['fileFormat', 'attribution'],
            '+expert' => [
                'onEachFeature',
                'pointToLayer',
            ],
        ],
    ],

    'metasubselectpalettes' => [
        'fileFormat' => [
            '!' => ['file'],
        ],
    ],

    'metasubpalettes' => [
        'spiderfyOnMaxZoom' => ['spiderfyDistanceMultiplier'],
        'deferred'          => ['cache'],
        'cache'             => ['cacheLifeTime'],
        'riseOnHover'       => ['riseOffset'],
    ],

    'fields' => [
        'id'                             => ['sql' => 'int(10) unsigned NOT NULL auto_increment'],
        'pid'                            => ['sql' => "int(10) unsigned NOT NULL default '0'"],
        'sorting'                        => ['sql' => "int(10) unsigned NOT NULL default '0'"],
        'tstamp'                         => ['sql' => "int(10) unsigned NOT NULL default '0'"],
        'title'                          => [
            'exclude'   => true,
            'inputType' => 'text',
            'search'    => true,
            'eval'      => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'alias'                          => [
            'exclude'   => true,
            'inputType' => 'text',
            'search'    => true,
            'eval'      => [
                'mandatory'   => false,
                'maxlength'   => 255,
                'tl_class'    => 'w50',
                'unique'      => true,
                'nullIfEmpty' => true,
                'doNotCopy'   => true,
            ],
            'sql'       => 'varchar(255) NULL',
        ],
        'type'                           => [
            'exclude'   => true,
            'inputType' => 'select',
            'filter'    => true,
            'eval'      => [
                'mandatory'          => true,
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'submitOnChange'     => true,
                'chosen'             => true,
                'helpwizard'         => true,
            ],
            'reference' => &$GLOBALS['TL_LANG']['cowegis_layer'],
            'sql'       => "varchar(32) NOT NULL default ''",
        ],
        'deferred'                       => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => true, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'groupType'                      => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'mandatory'      => true,
                'tl_class'       => 'w50',
                'submitOnChange' => true,
                'helpwizard'     => true,
            ],
            'default'   => 'layer',
            'options'   => ['layer', 'feature'],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['groupTypes'],
            'sql'       => "varchar(32) NOT NULL default ''",
        ],
        'reference'                      => [
            'exclude'    => true,
            'inputType'  => 'select',
            'eval'       => [
                'mandatory'          => true,
                'tl_class'           => 'w50',
                'chosen'             => true,
                'includeBlankOption' => true,
            ],
            'foreignKey' => 'tl_cowegis_layer.title',
            'sql'        => "int(10) unsigned NOT NULL default '0'",
        ],
        'standalone'                     => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'onEachFeature'                  => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|javascript',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'pointToLayer'                   => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|javascript',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'showCoverageOnHover'            => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'zoomToBoundsOnClick'            => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'spiderfyOnMaxZoom'              => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => true, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'removeOutsideVisibleBounds'     => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'animateAddingMarkers'           => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'disableClusteringAtZoom'        => [
            'exclude'   => true,
            'inputType' => 'select',
            'default'   => null,
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'maxClusterRadius'               => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'singleMarkerMode'               => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => false, 'isBoolean' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'polygonOptions'                 => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|json',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'spiderfyDistanceMultiplier'     => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'iconCreateFunction'             => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|javascript',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'tileUrl'                        => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => ['maxlength' => 255, 'tl_class' => 'w50', 'mandatory' => true],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'minZoom'                        => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'maxZoom'                        => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'maxNativeZoom'                  => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'tileSize'                       => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'subdomains'                     => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => ['maxlength' => 16, 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'varchar(16) default NULL',
        ],
        'errorTileUrl'                   => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => ['maxlength' => 255, 'tl_class' => 'w50'],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'attribution'                    => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => [
                'maxlength'   => 255,
                'tl_class'    => 'clr long',
                'allowHtml'   => true,
                'nullIfEmpty' => true,
            ],
            'sql'       => 'varchar(255) default NULL',
        ],
        'tms'                            => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'noWrap'                         => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'zoomOffset'                     => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'clr w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'zoomReverse'                    => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'opacity'                        => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '1.0',
            'eval'      => ['mandatory' => false, 'maxlength' => 4, 'rgxp' => 'digit', 'tl_class' => 'w50 clr'],
            'sql'       => "varchar(4) NOT NULL default ''",
        ],
        'zIndex'                         => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'unloadvisibleTiles'             => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'updateWhenIdle'                 => [
            'exclude'   => true,
            'inputType' => 'select',
            'options'   => ['0', '1'],
            'default'   => null,
            'eval'      => ['tl_class' => 'w50', 'nullIfEmpty' => true, 'includeBlankOption' => true],
            'sql'       => 'char(5) default NULL',
        ],
        'detectRetina'                   => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'bounds'                         => [
            'exclude'   => true,
            'inputType' => 'leaflet_geocode',
            'eval'      => [
                'maxlength'   => 255,
                'multiple'    => true,
                'size'        => 2,
                'tl_class'    => 'clr',
                'nullIfEmpty' => true,
            ],
            'sql'       => 'mediumblob NULL',
        ],
        'cache'                          => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'cacheLifeTime'                  => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 0,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql'       => "int(10) unsigned NOT NULL default '0'",
        ],
        'overpassQuery'                  => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'overpassEndpoint'               => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => 'varchar(255) NULL default NULL',
        ],
        'overpassCallback'               => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|javascript',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'minZoomIndicatorPosition'       => [
            'exclude'   => true,
            'inputType' => 'select',
            'options'   => ['topleft', 'topright', 'bottomleft', 'bottomright'],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_layer'],
            'eval'      => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50', 'helpwizard' => true],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'minZoomIndicatorMessage'        => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => ['tl_class' => 'clr w50'],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'minZoomIndicatorMessageNoLayer' => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => '',
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'debug'                          => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'amenityIcons'                   => [
            'exclude'   => true,
            'inputType' => 'multiColumnWizard',
            'eval'      => [
                'tl_class'     => 'leaflet-mcw leaflet-mcw-amenity-icons',
                'style'        => 'max-width: 800px',
                'columnFields' => [
                    'amenity' => [
                        'exclude'   => true,
                        'inputType' => 'select',
                        'eval'      => [
                            'mandatory' => false,
                            'style'     => 'width: 100%',
                            'chosen'    => true,
                        ],
                    ],
                    'icon'    => [
                        'label'     => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['amenityIcon'],
                        'exclude'   => true,
                        'inputType' => 'select',
                        'eval'      => [
                            'mandatory' => false,
                            'style'     => 'width: 100%',
                            'chosen'    => true,
                        ],
                    ],
                ],
            ],
            'sql'       => 'blob NULL',
        ],
        'overpassPopup'                  => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'preserveTags'   => true,
                'decodeEntities' => true,
                'allowHtml'      => true,
                'rte'            => 'ace|javascript',
                'tl_class'       => 'clr',
            ],
            'sql'       => 'mediumtext NULL',
        ],
        'fileFormat'                     => [
            'exclude'   => true,
            'inputType' => 'select',
            'filter'    => true,
            'eval'      => [
                'mandatory'          => true,
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'submitOnChange'     => true,
                'chosen'             => true,
                'helpwizard'         => true,
            ],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_layer']['fileFormats'],
            'sql'       => "varchar(32) NOT NULL default ''",
        ],
        'file'                           => [
            'exclude'   => true,
            'inputType' => 'fileTree',
            'eval'      => [
                'filesOnly' => true,
                'fieldType' => 'radio',
                'mandatory' => true,
                'tl_class'  => 'clr',
            ],
            'sql'       => 'binary(16) NULL',
        ],
        'icon'                           => [
            'exclude'    => true,
            'inputType'  => 'select',
            'eval'       => [
                'mandatory'          => false,
                'tl_class'           => 'clr w50',
                'chosen'             => true,
                'includeBlankOption' => true,
            ],
            'foreignKey' => 'tl_cowegis_icon.title',
            'sql'        => "int(10) unsigned NOT NULL default '0'",
        ],
        'popup'                          => [
            'exclude'    => true,
            'inputType'  => 'select',
            'eval'       => [
                'mandatory'          => false,
                'tl_class'           => 'w50',
                'chosen'             => true,
                'includeBlankOption' => true,
            ],
            'foreignKey' => 'tl_cowegis_popup.title',
            'sql'        => "int(10) unsigned NOT NULL default '0'",
        ],
        'tooltip'                        => [
            'exclude'    => true,
            'inputType'  => 'select',
            'eval'       => [
                'mandatory'          => false,
                'tl_class'           => 'w50',
                'chosen'             => true,
                'includeBlankOption' => true,
            ],
            'foreignKey' => 'tl_cowegis_tooltip.title',
            'sql'        => "int(10) unsigned NOT NULL default '0'",
        ],
        'interactive'                    => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'draggable'                      => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'keyboard'                       => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'zIndexOffset'                   => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 0,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'riseOnHover'                    => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'riseOffset'                     => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 0,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'clr w50', 'nullIfEmpty' => true],
            'sql'       => 'int(5) NULL',
        ],
        'vectors' => [
            'inputType' => 'textarea',
            'eval'      => [
                'rte'               => 'ace|json',
                'useRawRequestData' => true,
            ],
            'sql'       => 'blob NULL',
        ],
    ],
];
