<?php

declare(strict_types=1);

use Contao\DC_Table;

$GLOBALS['TL_DCA']['tl_cowegis_map'] = [
    'config' => [
        'dataContainer'    => DC_Table::class,
        'enableVersioning' => true,
        'ctable'           => ['tl_cowegis_map_layer', 'tl_cowegis_map_pane', 'tl_cowegis_control'],
        'sql'              => [
            'keys' => [
                'id'    => 'primary',
                'alias' => 'unique',
            ],
        ],
    ],

    'list' => [
        'sorting'           => [
            'mode'        => 1,
            'fields'      => ['title'],
            'panelLayout' => 'search,limit',
            'flag'        => 1,
        ],
        'label'             => [
            'fields' => ['title', 'alias'],
            'format' => '%s <span class="tl_gray">[%s]</span>',
        ],
        'global_operations' => [
            'api_docs' => [
                'icon'  => 'bundles/cowegiscontao/img/api_docs.png',
                'route' => 'cowegis_contao_backend_api_docs',
            ],
            'all'      => [
                'href'       => 'act=select',
                'class'      => 'header_edit_all',
                'attributes' => 'onclick="Backend.getScrollOffset();" accesskey="e"',
            ],
        ],
        'operations'        => [
            'edit'     => [
                'href'       => 'act=edit',
                'icon'       => 'header.gif',
                'attributes' => 'accesskey="e"',
            ],
            'layers'   => [
                'href'       => 'table=tl_cowegis_layer',
                'icon'       => 'bundles/cowegiscontao/img/layers.png',
                'attributes' => 'onclick="Backend.getScrollOffset();" accesskey="l"',
            ],
            'controls' => [
                'href'       => 'table=tl_cowegis_control',
                'icon'       => 'bundles/cowegiscontao/img/control.png',
                'attributes' => 'onclick="Backend.getScrollOffset();" accesskey="c"',
            ],
            'panes'    => [
                'href'       => 'table=tl_cowegis_map_pane',
                'icon'       => 'bundles/cowegiscontao/img/panes.png',
                'attributes' => 'onclick="Backend.getScrollOffset();" accesskey="p"',
            ],
            'copy'     => [
                'href' => 'act=copy',
                'icon' => 'copy.gif',
            ],
            'delete'   => [
                'icon'       => 'delete.gif',
                'attributes' => 'onclick="if(!confirm(\'' . ($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? '')
                    . '\'))return false;Backend.getScrollOffset()"',
            ],
            'show'     => [
                'href' => 'act=show',
                'icon' => 'show.gif',
            ],
        ],
    ],

    'metapalettes'    => [
        'default' => [
            'title'       => ['title', 'alias'],
            'zoom'        => ['center', 'zoom', 'adjustZoomExtra'],
            'bounds'      => ['adjustBounds', 'dynamicLoad', 'boundsPadding'],
            'locate'      => ['locate'],
            'interaction' => [
                'dragging',
                'touchZoom',
                'scrollWheelZoom',
                'doubleClickZoom',
                'boxZoom',
                'tap',
                'keyboard',
                'gestureHandling',
            ],
            'behaviour'   => [
                'zoomControl',
                'trackResize',
                'closePopupOnClick',
                'bounceAtZoomLimits',
            ],
            'assets'      => [
                ':hide',
                'defaultAssets',
                'assets',
            ],
            'expert'      => [
                'options',
                'cache',
            ],
        ],
    ],
    'metasubpalettes' => [
        'keyboard'        => [
            'keyboardPanOffset',
            'keyboardZoomOffset',
        ],
        'adjustZoomExtra' => [
            'minZoom',
            'maxZoom',
            'zoomSnap',
            'zoomDelta',
        ],
        'locate'          => [
            ':hide',
            'locateWatch',
            'locateSetView',
            'locateMaxZoom',
            'locateTimeout',
            'locateMaximumAge',
            'enableHighAccuracy',
        ],
        'cache'           => ['cacheLifeTime'],
    ],

    'fields' => [
        'id'                 => ['sql' => 'int(10) unsigned NOT NULL auto_increment'],
        'tstamp'             => ['sql' => "int(10) unsigned NOT NULL default '0'"],
        'title'              => [
            'exclude'   => true,
            'inputType' => 'text',
            'search'    => true,
            'eval'      => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'alias'              => [
            'exclude'   => true,
            'inputType' => 'text',
            'search'    => true,
            'eval'      => [
                'mandatory'   => false,
                'maxlength'   => 255,
                'tl_class'    => 'w50',
                'unique'      => true,
                'doNotCopy'   => true,
                'nullIfEmpty' => true,
            ],
            'sql'       => 'varchar(255) NULL',
        ],
        'center'             => [
            'exclude'   => true,
            'inputType' => 'cowegis_geocode',
            'eval'      => [
                'maxlength'   => 255,
                'tl_class'    => 'clr',
                'nullIfEmpty' => true,
            ],
            'sql'       => 'varchar(255) NULL',
        ],
        'zoom'               => [
            'exclude'   => true,
            'inputType' => 'select',
            'default'   => null,
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'adjustZoomExtra'    => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'minZoom'            => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'maxZoom'            => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'zoomSnap'           => [
            'exclude'   => true,
            'inputType' => 'text',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'varchar(4) NULL',
        ],
        'zoomDelta'          => [
            'exclude'   => true,
            'inputType' => 'text',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'varchar(4) NULL',
        ],
        'dragging'           => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'touchZoom'          => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'scrollWheelZoom'    => [
            'exclude'   => true,
            'inputType' => 'select',
            'options'   => ['1', 'center'],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_map']['zoomValues'],
            'default'   => true,
            'eval'      => [
                'tl_class'           => 'w50',
                'helpwizard'         => true,
                'includeBlankOption' => true,
                'blankOptionLabel'   => &$GLOBALS['TL_LANG']['tl_cowegis_map']['zoomValues'][''][0],
            ],
            'sql'       => "char(6) NOT NULL default ''",
        ],
        'doubleClickZoom'    => [
            'exclude'   => true,
            'inputType' => 'select',
            'options'   => ['1', 'center'],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_map']['zoomValues'],
            'default'   => true,
            'eval'      => [
                'tl_class'           => 'w50',
                'helpwizard'         => true,
                'includeBlankOption' => true,
                'blankOptionLabel'   => &$GLOBALS['TL_LANG']['tl_cowegis_map']['zoomValues'][''][0],
            ],
            'sql'       => "char(6) NOT NULL default ''",
        ],
        'boxZoom'            => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'tap'                => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'trackResize'        => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'bounceAtZoomLimits' => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'closeOnClick'       => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'keyboard'           => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'keyboardPanOffset'  => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 80,
            'eval'      => ['mandatory' => true, 'maxlength' => 4, 'rgxp' => 'digit', 'tl_class' => 'clr w50'],
            'sql'       => "int(4) NOT NULL default '80'",
        ],
        'keyboardZoomOffset' => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 1,
            'eval'      => ['mandatory' => true, 'maxlength' => 4, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql'       => "int(4) NOT NULL default '1'",
        ],
        'gestureHandling'    => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'zoomControl'        => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'options'            => [
            'exclude'   => true,
            'inputType' => 'textarea',
            'eval'      => [
                'tl_class'  => 'clr lng',
                'allowHtml' => true,
                'style'     => 'min-height: 40px;',
                'rte'       => 'ace|json',
            ],
            'sql'       => 'text NULL',
        ],
        'adjustBounds'       => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'options'   => ['load', 'deferred'],
            'reference' => &$GLOBALS['TL_LANG']['tl_cowegis_map']['adjustBoundsOptions'],
            'eval'      => ['tl_class' => 'clr w50', 'multiple' => true, 'helpwizard' => true],
            'sql'       => "varchar(255) NOT NULL default ''",
        ],
        'dynamicLoad'        => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'clr m12 w50', 'submitOnChange' => false],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'boundsPadding'      => [
            'exclude'   => true,
            'inputType' => 'text',
            'eval'      => [
                'maxlength'          => 32,
                'tl_class'           => 'w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'varchar(32) NULL',
        ],
        'locate'             => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'locateWatch'        => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'locateSetView'      => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'eval'      => ['tl_class' => 'w50', 'submitOnChange' => false],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'locateTimeout'      => [
            'exclude' => true,
            'default' => null,
            'eval'    => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'     => 'int(9) NULL',
        ],
        'locateMaximumAge'   => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => null,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50', 'nullIfEmpty' => true],
            'sql'       => 'int(9) NULL',
        ],
        'enableHighAccuracy' => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12'],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'locateMaxZoom'      => [
            'exclude'   => true,
            'inputType' => 'select',
            'eval'      => [
                'maxlength'          => 4,
                'rgxp'               => 'digit',
                'tl_class'           => 'clr w50',
                'includeBlankOption' => true,
                'nullIfEmpty'        => true,
            ],
            'sql'       => 'int(4) NULL',
        ],
        'defaultAssets'      => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => true,
            'eval'      => ['tl_class' => 'w50'],
            'sql'       => "char(1) NOT NULL default '1'",
        ],
        'assets'             => [
            'exclude'   => true,
            'inputType' => 'fileTree',
            'eval'      => [
                'multiple'   => true,
                'fieldType'  => 'checkbox',
                'filesOnly'  => true,
                'extensions' => 'css,js',
                'orderField' => 'assetsOrder',
                'tl_class'   => 'clr',
            ],
            'sql'       => 'blob NULL',
        ],
        'assetsOrder'        => [
            'label' => &$GLOBALS['TL_LANG']['MSC']['sortOrder'],
            'sql'   => 'blob NULL',
        ],
        'cache'              => [
            'exclude'   => true,
            'inputType' => 'checkbox',
            'default'   => false,
            'eval'      => ['tl_class' => 'w50 m12', 'submitOnChange' => true],
            'sql'       => "char(1) NOT NULL default ''",
        ],
        'cacheLifeTime'      => [
            'exclude'   => true,
            'inputType' => 'text',
            'default'   => 0,
            'eval'      => ['maxlength' => 5, 'rgxp' => 'digit', 'tl_class' => 'w50'],
            'sql'       => "int(9) NOT NULL default '0'",
        ],
    ],
];
