<?php

declare(strict_types=1);

namespace Cowegis\Bundle\Contao\Map\Layer\Markers\Hydrator;

use Cowegis\Bundle\Contao\Hydrator\Options\ConfigurableOptionsHydrator;
use Cowegis\Bundle\Contao\Model\LayerModel;
use Cowegis\Core\Definition\UI\Marker;
use Cowegis\Core\Provider\Context;
use function get_class;

final class MarkerOptionsHydrator extends ConfigurableOptionsHydrator
{
    protected const OPTIONS = [
        'interactive',
        'draggable',
        'keyboard',
        'opacity',
        'zIndexOffset',
        'riseOnHover'
    ];

    protected const CONDITIONAL_OPTIONS = [
        'riseOnHover' => ['riseOffset']
    ];

    public function hydrate(object $data, object $definition, Context $context) : void
    {
        parent::hydrate($data, $definition, $context); // TODO: Change the autogenerated stub
    }

    protected function supportsDefinition(object $definition) : bool
    {
        return $definition instanceof Marker;
    }

    protected function supportsData(object $data) : bool
    {
        return $data instanceof LayerModel;
    }
}
